extends: standard
plugins:
  - standard
  - promise
  - compat
rules:
  compat/compat: 2
env:
  browser: true
  node: false
  es6: false
  commonjs: true
parserOptions:
  sourceType: module
